apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-app-kustomize
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-deployment-v1/demo/argo-helm-kustomize/my-app-deployment/overlays/dev
    repoURL: git@gitlab.com:kubelab-gitops-playground/argocd-infrastructure-design.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: true
