apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-app-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: appbundle-project-dev
  source:
    path: app-of-apps/argocd-app-of-apps-parent/argocd/apps-children/dev
    repoURL: https://github.com/sjondegast/argo-playground.git
    targetRevision: HEAD
